name: Laravel CI with SonarCloud

on:
  push:
    branches:
      - main
      - develop
      - feature/footer
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer, phpunit
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup Laravel Environment
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run PHPUnit Tests with Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_php-pulse
            -Dsonar.php.coverage.reportPaths=coverage.xml
