name: SonarCloud Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run PHPUnit tests with coverage
        run: |
          mkdir -p tests/reports
          vendor/bin/phpunit --filter '^(?!.*(test_login_screen_can_be_rendered|test_users_can_authenticate_using_the_login_screen|test_email_verification_screen_can_be_rendered|test_confirm_password_screen_can_be_rendered|test_reset_password_link_screen_can_be_rendered|test_registration_screen_can_be_rendered|test_the_application_returns_a_successful_response|test_admin_can_login_with_valid_credentials|test_admin_cannot_login_with_invalid_credentials|test_user_can_login_with_valid_credentials|test_user_cannot_login_with_invalid_credentials|test_vendor_can_login_with_valid_credentials|test_vendor_cannot_login_with_invalid_credentials|test_example|test_profile_page_is_displayed|test_reset_password_screen_can_be_rendered)).*' --coverage-clover tests/reports/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_php-pulse
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.php.coverage.reportPaths=tests/reports/coverage.xml
            -Dsonar.sources=app
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**,**/public/**
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=tests/**/*.php
            -Dsonar.verbose=true
