name: SonarCloud Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPUnit tests with coverage
        run: |
          mkdir -p tests/reports
          vendor/bin/phpunit --coverage-clover tests/reports/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_php-pulse
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.php.coverage.reportPaths=tests/reports/coverage.xml
            -Dsonar.sources=app
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**,**/public/**
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=tests/**/*.php
            -Dsonar.language=php
            -Dsonar.php.file.suffixes=.php
            -Dsonar.verbose=true
