name: SonarCloud Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root     
          MYSQL_DATABASE: ecommerce      
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u$MYSQL_ROOT_PASSWORD || exit 1"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql
          coverage: xdebug

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Disable Composer Pubkey Check (Optional)
        run: composer config --global secure-http false

      - name: Remove Vendor & Clear Cache (Force Clean)
        run: |
          rm -rf vendor
          composer clear-cache

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Setup Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=ecommerce" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          php artisan config:clear
          php artisan config:cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run PHPUnit Tests with Coverage
        run: |
          mkdir -p tests/reports
          vendor/bin/phpunit --coverage-clover tests/reports/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_php-pulse
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.php.coverage.reportPaths=tests/reports/coverage.xml
            -Dsonar.sources=app
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**,**/public/**
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=tests/**/*.php
            -Dsonar.language=php
            -Dsonar.php.file.suffixes=.php
            -Dsonar.verbose=true

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tests/reports/
          retention-days: 5
