name: Laravel CI with SonarCloud

on:
  push:
    branches:
      - '**'  # For all branches (main, develop, feature/*, etc.)
  pull_request:
    branches:
      - '**'  # For pull requests targeting any branch

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .env for Database
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=ecommerce" >> .env
          echo "DB_USERNAME=test_user" >> .env
          echo "DB_PASSWORD=test_pass" >> .env

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --no-scripts
          composer dump-autoload --optimize

      - name: Update Composer Dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Install Missing Package
        run: composer require php-flasher/flasher-toastr-laravel --with-all-dependencies

      - name: Refresh Composer Autoload
        run: composer dump-autoload --optimize

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run PHPUnit Tests (No Filter)
        run: php artisan test

      - name: List Files in Current Directory (For Debugging)
        run: ls -alh

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: storage/test-coverage/coverage.xml  # Ensure this is the correct path to your coverage file

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.php.coverage.reportPaths=storage/test-cove
